Added testing functionality
fbaumdicker/goldfinder pull request #5
Opened 2024-09-08 15:17 UTC by emilpaulitz

This will allow easier further developments (like addressing #4 ). The tests work on ubuntu and windows.
Also, I found a small bug during testing, the fix is included in this pull request.
I renamed one of the output files' ending to reflect its format. The readme is edited correspondingly.
Lastly, I added some information regarding errors during installation to the readme.

2025-01-23 16:20 UTC, fbaumdicker commented on example_files/roary_mini_example.csv
> +a,abc,hypothetical protein,,,,,,,,,,,,x,,x,x,
can we use something else than "abc" for the gene name, as this might be confusing with the genes a, b, c. How about "gene_a"?

2025-01-23 16:21 UTC, fbaumdicker commented on example_files/roary_mini_example.csv
> +a,abc,hypothetical protein,,,,,,,,,,,,x,,x,x,
or "geneA"

2025-01-23 16:30 UTC, fbaumdicker commented
Besides this one minor naming, this looks good to me.
Add some point we might also want to include a test for the `-add` option but this is probably better done in a larger example data set. So for now these tests should be a great start. Thanks!

2025-02-20 19:41 UTC, fbaumdicker commented on example_files/roary_mini_example.csv
> +a,abc,hypothetical protein,,,,,,,,,,,,x,,x,x,
We can also change this later. Will merge now.

2025-02-20 20:08 UTC, fbaumdicker requested changes
Running goldfinder.py --tests results in 
`(1/3) Running tab test...
(2/3) Running roary test...
(3/3) Running matrix test...
Tests failed. Following files could not be compared:
tab/simultaneous_association_significant_pairs.txt
roary/simultaneous_association_significant_pairs.txt
matrix/simultaneous_association_significant_pairs.txt
Please check files and then delete golfinder/tmp folder manually.
`

2025-02-20 20:08 UTC, fbaumdicker commented on goldfinder/goldfinder.py
> +    parser.add_argument("-t", "--tree", nargs='?', const=None,
The -t option is required by design. Please keep this as a required option

2025-02-21 09:53 UTC, emilpaulitz commented on example_files/roary_mini_example.csv
> +a,abc,hypothetical protein,,,,,,,,,,,,x,,x,x,
Sorry, did not see this earlier! Done

2025-02-21 09:55 UTC, emilpaulitz commented on goldfinder/goldfinder.py
> +    parser.add_argument("-t", "--tree", nargs='?', const=None,
No idea how I did not catch the tests not running through before. Sorry! Forgot to specify the changed file ending in the expected test result files.

2025-02-21 09:58 UTC, emilpaulitz commented on goldfinder/goldfinder.py
> +    parser.add_argument("-t", "--tree", nargs='?', const=None,
The -t option is still required, as is -i (run  python goldfinder/goldfinder.py -i example_files/matrix_mini_example.csv to get the error that -t is missing). 
``

I had to code it at line 120 so that the user can run --tests without getting the error that -i and -t are missing. Is this fine?

2025-02-21 10:19 UTC, fbaumdicker commented on goldfinder/goldfinder.py
> +    parser.add_argument("-t", "--tree", nargs='?', const=None,
Ah I see, this is fine then.

2025-02-21 10:33 UTC, fbaumdicker commented
The tests in your branch are now all passing. However, we meanwhile had a bugfix in b47c9e35da0e4c22c5dfa12eb68fab41f9c6eab3 that changed the output. When using this new scoring function the tests consequently fail. If you generate the expected test files with this updated scoring function the tests should also pass after merging to main.

2025-02-21 10:51 UTC, fbaumdicker requested changes
When the expected test files have been generated with the newest version of scoring.py from the main branch this can be merged.

2025-02-21 12:19 UTC, emilpaulitz commented
Rebased and updated expected files

2025-02-21 15:04 UTC, fbaumdicker approved these changes

2025-02-21 15:04 UTC, merged